name: color_picker
description: An app made in flutter to help people choose the colors they will
  use in their projects!

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  color: ^3.0.0
  flutter_colorpicker: ^0.5.0
  fl_toast: ^3.1.0
  font_awesome_flutter: ^9.1.0
  image_picker: 0.8.3+2
  path: ^1.8.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.9
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1

flutter:
  uses-material-design: true
  # assets:
  #   - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
  adaptive_icon_background: "assets/background.jpg"
