name: color_picker
description: An app made in Flutter to help people choose the colors they will
  use in their projects!

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  color: ^3.0.0
  flutter_colorpicker: ^0.6.0
  fl_toast: ^3.1.0
  font_awesome_flutter: ^9.2.0
  image_picker: 0.8.4+4
  path: ^1.8.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.12
  url_strategy: ^0.2.0
  bitsdojo_window: ^0.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  # assets:
  #   - assets/

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icon.png"