name: color_picker
description: An app made in flutter to help people choose the colors they will use in their projects!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  color: ^2.1.1
  path:
  sqflite: ^1.3.1
  loading_animations: ^2.1.0
  provider: ^2.0.0
  image_picker: 0.6.7+4
  shared_preferences: ^0.5.8
  flutter_styled_toast: ^1.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
  adaptive_icon_background: "assets/background.jpg"